name: Bug report
about: Create a report to help us improve
title: "[Bug] "
labels: bug
body:
  - type: textarea
    attributes: { label: Steps to reproduce }
  - type: textarea
    attributes: { label: Expected behavior }
  - type: textarea
    attributes: { label: Screenshots / logs }
